# Generated by Django 6.0.4 on 2026-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
