# Generated by Django 6.0.4 on 2026-06-02 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_rating_given_booking_review_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 2, 13, 49, 43, 954457, tzinfo=datetime.timezone.utc)),
        ),
    ]
