# Generated by Django 6.0.4 on 2026-06-04 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_admin_notes_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 4, 14, 32, 15, 956630, tzinfo=datetime.timezone.utc)),
        ),
    ]
