# Generated by Django 6.0.4 on 2026-06-06 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin_notes',
            new_name='admin_messages',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
